# Generated by Django 4.1.7 on 2023-04-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=100)),
                ('salary', models.BigIntegerField()),
                ('company', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('locations', models.CharField(max_length=50)),
            ],
        ),
    ]
